version: "3"
services:
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: my_wiremock
    command:
    - "--global-response-templating"
    - "--disable-gzip=true"
    ports:
      - "8084:8080"
    volumes:
      - $PWD/stubs:/home/wiremock:ro
    # environment:
      # WIREMOCK_OPTIONS: "--port=8089,--https-port=8088,--max-request-journal=1000,--local-response-templating,--root-dir=/home/wiremock/storage"